package com.ws101.tomacas.EcommerceApi.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;

import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a product category.
 *
 * <p>Maps to the {@code categories} table in the database. Categories
 * are used to group products together (e.g., Electronics, Clothing,
 * Footwear). Each category has a unique name and can contain multiple
 * products.</p>
 *
 * <h3>Relationships:</h3>
 * <ul>
 *   <li><b>One-to-Many</b> with {@link Product}: One category can
 *       have many products. The relationship is mapped by the
 *       {@code categoryEntity} field in the Product entity.</li>
 * </ul>
 *
 * @author Jules Ian C. Tomacas
 * @author Jovan P. Atencio
 */
@Entity
@Table(name = "categories")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "products")
@EqualsAndHashCode(exclude = "products")
public class Category {

    /**
     * Unique identifier for the category.
     * Auto-generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the category. Must be unique and cannot be null.
     * Examples: "Electronics", "Clothing", "Footwear".
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * One-to-Many relationship with {@link Product}.
     *
     * <p>One category can contain many products. Uses LAZY fetching
     * to avoid loading all products when only the category info is
     * needed. {@code CascadeType.ALL} propagates save/delete operations
     * from this category to its associated products.</p>
     *
     * <p>{@code @JsonIgnore} prevents infinite recursion during
     * JSON serialization (Category → Products → Category → ...).</p>
     */
    @OneToMany(mappedBy = "categoryEntity", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnore
    private List<Product> products = new ArrayList<>();
}
