package com.ws101.tomacas.EcommerceApi.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;

/**
 * JPA entity representing a single item within an {@link Order}.
 *
 * <p>Maps to the {@code order_items} table in the database. Each
 * order item links a specific {@link Product} to an {@link Order},
 * tracking the quantity purchased and the price at the time of
 * purchase (which may differ from the product's current price).</p>
 *
 * <h3>Relationships:</h3>
 * <ul>
 *   <li><b>Many-to-One</b> with {@link Order}: Many order items
 *       belong to one order. The foreign key {@code order_id}
 *       is stored in this table.</li>
 *   <li><b>Many-to-One</b> with {@link Product}: Many order items
 *       can reference the same product. The foreign key
 *       {@code product_id} is stored in this table.</li>
 * </ul>
 *
 * @author Jules Ian C. Tomacas
 * @author Jovan P. Atencio
 */
@Entity
@Table(name = "order_items")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"order", "product"})
@EqualsAndHashCode(exclude = {"order", "product"})
public class OrderItem {

    /**
     * Unique identifier for the order item.
     * Auto-generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Number of units of the product purchased in this line item. */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Price of the product at the time of purchase.
     * This is stored separately because product prices may change
     * after the order is placed.
     */
    @Column(nullable = false)
    private Double priceAtPurchase;

    /**
     * Many-to-One relationship with {@link Order}.
     *
     * <p>Multiple order items belong to a single order.
     * The foreign key column {@code order_id} is stored in this
     * table. Uses LAZY fetching for performance.
     * {@code @JsonIgnore} prevents circular serialization.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id")
    @JsonIgnore
    private Order order;

    /**
     * Many-to-One relationship with {@link Product}.
     *
     * <p>Multiple order items can reference the same product.
     * The foreign key column {@code product_id} is stored in this
     * table. Uses LAZY fetching for performance.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Product product;
}
