package com.ws101.tomacas.EcommerceApi.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a customer order.
 *
 * <p>Maps to the {@code orders} table in the database. An order
 * captures a customer's purchase, including their contact info,
 * the total amount, and the date the order was placed.</p>
 *
 * <h3>Relationships:</h3>
 * <ul>
 *   <li><b>One-to-Many</b> with {@link OrderItem}: One order can
 *       contain many order items. The relationship is mapped by
 *       the {@code order} field in the OrderItem entity.
 *       {@code orphanRemoval = true} ensures that removing an item
 *       from the list also deletes it from the database.</li>
 * </ul>
 *
 * @author Jules Ian C. Tomacas
 * @author Jovan P. Atencio
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "orderItems")
@EqualsAndHashCode(exclude = "orderItems")
public class Order {

    /**
     * Unique identifier for the order.
     * Auto-generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Full name of the customer who placed the order. */
    @Column(nullable = false)
    private String customerName;

    /** Email address of the customer. */
    @Column(nullable = false)
    private String customerEmail;

    /** Total monetary amount for this order in PHP. */
    @Column(nullable = false)
    private Double totalAmount;

    /** Timestamp of when the order was placed. */
    @Column(nullable = false)
    private LocalDateTime orderDate;

    /**
     * One-to-Many relationship with {@link OrderItem}.
     *
     * <p>One order contains many order items. Uses {@code CascadeType.ALL}
     * so that saving or deleting an order automatically propagates to
     * its items. {@code orphanRemoval = true} deletes items that are
     * removed from this list.</p>
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> orderItems = new ArrayList<>();
}
