package com.ws101.tomacas.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.EqualsAndHashCode;

/**
 * JPA entity representing an e-commerce product.
 *
 * <p>Maps to the {@code products} table in the database. Each product
 * has a unique auto-generated identifier, descriptive fields, pricing
 * info, inventory tracking, and an optional relationship to a
 * {@link Category} entity.</p>
 *
 * <h3>Relationships:</h3>
 * <ul>
 *   <li><b>Many-to-One</b> with {@link Category}: Many products can
 *       belong to one category. The foreign key {@code category_id}
 *       is stored in this table.</li>
 * </ul>
 *
 * @author Jules Ian C. Tomacas
 * @author Jovan P. Atencio
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "categoryEntity")
@EqualsAndHashCode(exclude = "categoryEntity")
public class Product {

    /**
     * Unique identifier for the product.
     * Auto-generated by the database using the IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Display name of the product. Cannot be null. */
    @Column(nullable = false)
    private String name;

    /** Detailed description of the product. Stored as TEXT for longer content. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Price of the product in PHP. Must be a positive value. */
    @Column(nullable = false)
    private Double price;

    /**
     * Category name as a plain string.
     * Kept for backward compatibility with existing API responses.
     */
    @Column(nullable = false)
    private String category;

    /** Number of units currently available in stock. Must be non-negative. */
    @Column(nullable = false)
    private Integer stockQuantity;

    /** URL pointing to the product image. This field is optional. */
    private String imageUrl;

    /**
     * Many-to-One relationship with {@link Category}.
     *
     * <p>Multiple products can belong to a single category.
     * The foreign key column {@code category_id} is stored in
     * this (products) table. Uses LAZY fetching for performance.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category categoryEntity;
}
