package com.ws101.tomacas.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.List;

/**
 * JPA entity representing an application user with security credentials.
 *
 * <p>Implements Spring Security's {@link UserDetails} interface so that
 * the framework can use this entity directly for authentication and
 * authorization. Passwords are stored as BCrypt hashes.</p>
 *
 * <p>Each user has a single {@link Role} that determines their
 * access level throughout the system.</p>
 *
 * @author Jules Ian C. Tomacas
 * @see Role
 * @see UserDetails
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    /** Unique identifier for the user. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Login username. Must be unique across all users. */
    @Column(nullable = false, unique = true)
    private String username;

    /** BCrypt-hashed password. Never stored in plain text. */
    @Column(nullable = false)
    private String password;

    /** The user's assigned role (USER, SELLER, or ADMIN). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /**
     * Returns the authorities granted to the user.
     *
     * <p>Converts the user's {@link Role} into a Spring Security
     * {@link GrantedAuthority} with the {@code ROLE_} prefix, which
     * is required by {@code hasRole()} authorization checks.</p>
     *
     * @return a collection containing a single role-based authority
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority("ROLE_" + role.name()));
    }

    /** Returns {@code true} — accounts do not expire. */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /** Returns {@code true} — accounts are never locked. */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /** Returns {@code true} — credentials do not expire. */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /** Returns {@code true} — all accounts are enabled by default. */
    @Override
    public boolean isEnabled() {
        return true;
    }
}
